### ISSUE TITLE
Duplicate serial number in visualize-data

### ISSUE THREAD

**Issue by gvwilson** [rstudio-education/primers#19]
`visualize-data/` has both `01-Exploratory-Data-Analysis` and `01-bar-charts` - should the former not be `00`?

**Comment by garrettgman** [comment]
Yes, likely so. But the file names make their way into the shinyapps.io URLs that RStudio Cloud points to. In other words, changing the names will break the links. I'm content to leave things be because I worry that some teachers may have pointed their students directly to the tutorials on shinyapps.io—I don't want to break those links.
