### ISSUE TITLE
Why are we creating data.frames?

### ISSUE THREAD

**Issue by gvwilson** [rstudio-education/primers#66]
Why does the "Your turn" example use a `data.frame` instead of a tibble?

**Comment by garrettgman** [comment]
Because at that point in 04-Programming-Basics.Rmd, we are enumerating the core data types of the R language and we haven't yet introduced packages. Tibbles get their own introduction—and their own primer in Transform Data, but I prefer to have students think of tibbles as a type of data frame for debugging, help, and googling.
