### ISSUE TITLE
License for primers?

### ISSUE THREAD

**Issue by andreashandel** [rstudio-education/primers#80]
I'm in the process of developing materials for a data science class I will teach in fall. I would like to include parts of some of the primers in my exercises for students. Is such re-use and adaptation acceptable? I can't find the licensing conditions for the primers specified anywhere. Thanks!

**Comment by garrettgman** [comment]
@andreashandel You're free to have students visit and use the primers at https://rstudio.cloud/learn/primers. Some of the primers contain material that appears in a book copyrighted by O'Reilly Media. We've taken pains to make sure that the material is used in a legal way with the appropriate acknowledgements in the primers.

**Comment by andreashandel** [comment]
@garrettgman thanks for the quick reply. It doesn't quite answer my question. Instead (or in addition, I'm not sure yet) of having my students visit/use the existing primers, what I'd like to do is use the Rmd files of the primers, take parts from them and make my own learnr exercises tailored to my class. I forked the repository, so I have all the files, but before I embark on copy/paste/remix I want to make sure that's legally ok. Of course I'd be happy to label/reference every bit I take from the existing primers as such. But was/am not clear if a wholesale reuse of sections of the existing Rmd files for my purpose is ok. Thanks!

**Comment by garrettgman** [comment]
@andreashandel I can not answer your question precisely, because I do not know. If a primer has the following near the beginning, it contains material that O'Reilly Media has given us permission to republish.

```
Acknowledgements
These examples are excerpted from R for Data Science by Hadley Wickham and Garrett Grolemund, published by O’Reilly Media, Inc., 2016, ISBN: 9781491910399. You can purchase the book at shop.oreilly.com.
```

If it does not have this, then the material is 100% ours and I give @andreashandel  permission to reuse the material in the classroom, remixed or otherwise.

It is my belief that reuse of the remaining material in a classroom for educational purposes, and not published in a permanent way accessible to the general public, would be legally protected as Fair Use, but I am not a legal expert.

**Comment by andreashandel** [comment]
@garrettgman Thanks! This is specific enough that I know how to approach it.
